---
apiVersion: v1
kind: Service
metadata:
  namespace: dev    #必填，Pod所属的命名空间
  name: nacos
  labels:
    app: nacos
spec:
  type: NodePort
  ports:
    - port: 8848
      name: server
      targetPort: 8848
    - port: 9848
      name: client-rpc
      targetPort: 9848
    - port: 9849
      name: raft-rpc
      targetPort: 9849
    ## 兼容1.4.x版本的选举端口
    - port: 7848
      name: old-raft-rpc
      targetPort: 7848
  selector:
    app: nacos
---
apiVersion: apps/v1
kind: Deployment
metadata: #必填，元数据
  name: nacos       #必填，Pod名称
  namespace: dev    #必填，Pod所属的命名空间
  labels:
    app: nacos
spec: #必填，部署的详细定义
  replicas: 1 #必填，副本数量
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers: #必填，定义容器列表
        - name: nacos     #必填，容器名称
          image: nacos/nacos-server:v2.1.1-slim    #必填，容器的镜像名称
          ports: #需要暴露的端口库号列表
            - containerPort: 8848   #容器需要监听的端口号
              hostPort: 8848    #选填，容器所在主机需要监听的端口号，默认与Container相同
              protocol: TCP     #选填，端口协议，支持TCP和UDP，默认TCP
            - containerPort: 9848   #容器需要监听的端口号
              hostPort: 9848    #选填，容器所在主机需要监听的端口号，默认与Container相同
              protocol: TCP     #选填，端口协议，支持TCP和UDP，默认TCP
            - containerPort: 9555   #容器需要监听的端口号
              hostPort: 9555    #选填，容器所在主机需要监听的端口号，默认与Container相同
              protocol: TCP     #选填，端口协议，支持TCP和UDP，默认TCP
          env: #容器运行前需设置的环境变量列表
            - name: PREFER_HOST_MODE
              value: 'hostname'
            - name: MODE
              value: 'standalone'
            - name: SPRING_DATASOURCE_PLATFORM
              value: 'mysql'
            - name: MYSQL_SERVICE_HOST
              value: 'gz-cynosdbmysql-grp-irl7x9ar.sql.tencentcdb.com'
            - name: MYSQL_SERVICE_PORT
              value: '20716'
            - name: MYSQL_SERVICE_DB_NAME
              value: 'nacos_config'
            - name: MYSQL_SERVICE_USER
              value: 'kt_cloud8888'
            - name: MYSQL_SERVICE_PASSWORD
              value: 'Kt.cloud1234!@#$'
            - name: MYSQL_SERVICE_DB_PARAM
              value: 'characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai'