server:
  port: 8080
spring:
  application:
    name: commodity
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
    include: druid
# mybatis
mybatis-plus:
  mapper-locations: classpath:com/ark/center/commodity/infrastructure/db/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl