### 删除索引
DELETE {{es}}/sku

### 新建索引
PUT {{es}}/sku
Content-Type: application/json

{
  "mappings": {
    "properties": {
      "skuName": {
        "type": "text",
        "analyzer": "ik_smart"
      },
      "brandName": {
        "type": "keyword",
        "index": false
      },
      "createTime": {
        "type": "date",
        "format": "date_time",
        "index": false
      },
      "brandId": {
        "type": "long"
      },
      "salesPrice": {
        "type": "keyword"
      },
      "spuId": {
        "type": "keyword"
      },
      "updateTime": {
        "type": "date",
        "format": "date_time"
      },
      "_class": {
        "type": "keyword",
        "doc_values": false,
        "index": false
      },
      "categoryName": {
        "type": "keyword",
        "index": false
      },
      "skuId": {
        "type": "keyword",
        "index": true
      },
      "categoryId": {
        "type": "long"
      },
      "attrs": {
        "type": "nested",
        "properties": {
          "attrId": {
            "type": "long"
          },
          "_class": {
            "type": "keyword",
            "doc_values": false,
            "index": false
          },
          "attrValue": {
            "type": "keyword"
          },
          "attrName": {
            "type": "keyword",
            "index": false
          }
        }
      }
    }
  }
}

### 查看索引
GET {{es}}/sku

### 查看Mappings

GET {{es}}/sku/_mappings