server:
  port: 8083
spring:
  application:
    name: product
  # 默认dev环境
  profiles:
    default: dev
  main:
    # 是否允许循环依赖
    allow-circular-references: false
    # 当出现同名Bean的时候，允许后面的定义覆盖前面的定义
    allow-bean-definition-overriding: true
  # 微服务配置
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: http://es.ark.com:9200
    username: elastic
    connection-timeout: 1m
  cloud:
    nacos:
      discovery:
        enabled: ${nacos-discovery-enabled:}
        server-addr: ${discovery-server-addr:}
        namespace: ${nacos-discovery-namespace:}
        group: ${nacos-discovery-group:}
        ip: ${nacos-discovery-ip:}
      config:
        enabled: ${nacos-config-enabled:true}
        server-addr: ${config-server-addr:}
        namespace: ${nacos-config-namespace:}
        group: ${nacos-config-group:}
        file-extension: yml
        prefix: ${spring.application.name}
        refresh-enabled: true
        shared-configs:
          - common.yml
        # 开启检查spring.config.import
        import-check:
          enabled: true
      password: ${nacos-username}
      username: ${nacos-password}
    config:
      # 允许远程配置覆盖本地配置
      allow-override: ${config-allow-override:true}
  # Spring Config
  config:
    import:
      # 指定从nacos取的配置
      - nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
      - nacos:common.yml
mybatis-plus:
  mapper-locations: classpath:com/ark/center/*/infra/*/repository/db/xml/*.xml,classpath:com/ark/center/*/infra/*/db/xml/*.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ark-center-product
#logging:
#  level:
#    org:
#      elasticsearch:
#        client: trace
#    tracer: trace
---
# 本地开发环境，默认关闭服务注册以及关闭读取远程配置
spring:
  config:
    activate:
      on-profile: local
nacos-discovery-ip: ${NACOS_DISCOVERY_IP:}
nacos-discovery-namespace: ${NACOS_DISCOVERY_NAMESPACE:aaff0c75-80b1-4c85-ad3f-c625501368ba}
nacos-config-namespace: ${NACOS_CONFIG_NAMESPACE:aaff0c75-80b1-4c85-ad3f-c625501368ba}
discovery-server-addr: ${NACOS_DISCOVERY_SERVER_ADDR:127.0.0.1:8848}
config-server-addr: ${NACOS_CONFIG_SERVER_ADDR:127.0.0.1:8848}
nacos-username: ${NACOS_USERNAME:nacos}
nacos-password: ${NACOS_PASSWORD:nacos}
nacos-discovery-group: ${NACOS_DISCOVERY_GROUP:DEFAULT_GROUP}
nacos-config-group: ${NACOS_CONFIG_GROUP:DEFAULT_GROUP}
nacos-discovery-enabled: true
nacos-config-enabled: true
config-allow-override: true
---
# 开发环境
spring:
  config:
    activate:
      on-profile: dev
nacos-discovery-ip: ${NACOS_DISCOVERY_IP:}
nacos-discovery-namespace: ${NACOS_DISCOVERY_NAMESPACE:aaff0c75-80b1-4c85-ad3f-c625501368ba}
nacos-config-namespace: ${NACOS_CONFIG_NAMESPACE:aaff0c75-80b1-4c85-ad3f-c625501368ba}
discovery-server-addr: ${NACOS_DISCOVERY_SERVER_ADDR:127.0.0.1:8848}
config-server-addr: ${NACOS_CONFIG_SERVER_ADDR:127.0.0.1:8848}
nacos-username: ${NACOS_USERNAME:nacos}
nacos-password: ${NACOS_PASSWORD:nacos}
nacos-discovery-group: ${NACOS_DISCOVERY_GROUP:DEFAULT_GROUP}
nacos-config-group: ${NACOS_CONFIG_GROUP:DEFAULT_GROUP}
nacos-discovery-enabled: true
nacos-config-enabled: true
config-allow-override: true
---
# 集成测试环境
spring:
  config:
    activate:
      on-profile: sit
nacos-discovery-ip: ${NACOS_DISCOVERY_IP:}
nacos-discovery-namespace: ${NACOS_DISCOVERY_NAMESPACE:74ac3a8d-d15e-4f1b-a5cd-112f438c975d}
nacos-config-namespace: ${NACOS_CONFIG_NAMESPACE:74ac3a8d-d15e-4f1b-a5cd-112f438c975d}
discovery-server-addr: ${NACOS_DISCOVERY_SERVER_ADDR:127.0.0.1:8848}
config-server-addr: ${NACOS_CONFIG_SERVER_ADDR:127.0.0.1:8848}
nacos-username: ${NACOS_USERNAME:nacos}
nacos-password: ${NACOS_PASSWORD:nacos}
nacos-discovery-group: ${NACOS_DISCOVERY_GROUP:DEFAULT_GROUP}
nacos-config-group: ${NACOS_CONFIG_GROUP:DEFAULT_GROUP}
nacos-discovery-enabled: true
nacos-config-enabled: true
config-allow-override: true